title: simple

author: thisred

menus:
  about: /about/

site_icon: https://cdn.this.red/img/favicon.ico
head_img: https://cdn.this.red/img/favicon.ico
head_background: https://cdn.this.red/img/20191208144518.jpg
links:
  github: https://github.com/thisred
  qqgroup: https://qm.qq.com/cgi-bin/qm/qr?k=pT1Puvb_7GYijt_sdIjYTclo6q5Z8QXY&jump_from=webapi

background_color: "#ebebeb"
content_color: "white"
footer_color:
header_color: 